# Generated by Django 5.2.1 on 2025-10-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(default=0, upload_to='uploads/')),
                ('coursecode', models.CharField(default=0, max_length=20)),
                ('author', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
